#analyzer:
#  enable-experiment:
#    - non-nullable
#    - nonfunction-type-aliases

analyzer:
  errors:
    use_key_in_widget_constructors: ignore
    no_logic_in_create_state: ignore
    constant_identifier_names: ignore
    invalid_annotation_target: ignore # Suppress enum annotation warnings for builder-required annotations
