name: example

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  morphy_annotation:
    path: ../morphy_annotation

dev_dependencies:
  test: ^1.26.2
  build_runner: ^2.5.4
  morphy:
    path: ../morphy
  json_serializable: ^6.8.0
