name: example

environment:
  sdk: ">=3.1.3 <4.0.0"

#dependency_overrides:
#  morphy_annotation:
#    path: ../morphy_annotation

dependencies:
  json_serializable: ^6.7.1
  meta: any
  morphy:
    path: ../morphy

#  morphy: ^1.0.1

dev_dependencies:
  build_runner: ^2.4.6
  test: ^1.24.8

