name: example

environment:
  sdk: ">=3.1.3 <4.0.0"

dependency_overrides:
  morphy_annotation:
    path: ../morphy_annotation

dependencies:
  meta: any

  morphy:
    path: ../morphy

dev_dependencies:
  build_runner: ^2.4.6
  test: ^1.24.8

