name: factory_test
description: Test project for zikzak_morphy factory method functionality
version: 1.0.0

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  zikzak_morphy_annotation: ^2.8.0

dev_dependencies:
  test: ^1.26.2
  build_runner: ^2.5.4
  zikzak_morphy: ^2.8.0
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0
