name: zikzak_morphy
description: A powerful code generation package for Dart/Flutter that provides clean class definitions with copyWith, JSON serialization, toString, equality, and inheritance support
version: 2.1.0
homepage: https://github.com/arrrrny/morphy

environment:
  sdk: ">=3.8.0 <4.0.0"

# dependency_overrides:
#   morphy_annotation:
#     git:
#       url: https://github.com/arrrrny/morphy.git
#       path: morphy_annotation
#       ref: git-ref
dependencies:
  zikzak_morphy_annotation: ^2.1.0

dev_dependencies:
  build_runner: ^2.5.4
  json_serializable: ^6.8.0
  test: ^1.26.2
