name: morphy
description: Provides a clean class definition with extra functionality including; copy with, json serializable, tostring, equals that supports inheritance and polymorphism
version: 2.0.0
homepage: https://github.com/atreeon/morphy

environment:
  sdk: ">=3.1.3 <4.0.0"

# dependency_overrides:
#   morphy_annotation:
#     git:
#       url: https://github.com/arrrrny/morphy.git
#       path: morphy_annotation
#       ref: git-ref
publish_to: none
dependencies:
  morphy_annotation:
    git:
      url: https://github.com/arrrrny/morphy.git
      path: morphy_annotation
      ref: git-ref
  analyzer: ">=6.0.0 <=7.0.0"
  build: ^2.1.0
  source_gen: ^1.1.1
  dartx: ^1.2.0
  quiver: ^3.2.1
  path: ^1.8.1

dev_dependencies:
  build_runner: ^2.4.6
  test: ^1.24.8
