name: morphy
description: Provides a clean class definition with extra functionality including; copy with, json serializable, tostring, equals that supports inheritance and polymorphism
version: 2.0.0
homepage: https://github.com/atreeon/morphy

environment:
  sdk: ">=3.8.0 <4.0.0"

# dependency_overrides:
#   morphy_annotation:
#     git:
#       url: https://github.com/arrrrny/morphy.git
#       path: morphy_annotation
#       ref: git-ref
publish_to: none
dependencies:
  morphy_annotation:
    path: ../morphy_annotation
  analyzer: ^7.5.7
  build: ^2.5.4
  source_gen: ^2.0.0
  dartx: ^1.2.0
  quiver: ^3.2.2
  path: ^1.9.0

dev_dependencies:
  build_runner: ^2.5.4
  test: ^1.26.2
