name: ZikZak Morphy CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: dart:latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup zikzak_morphy_annotation
        working-directory: ./zikzak_morphy_annotation
        run: |
          dart pub get
          dart analyze

      - name: Setup zikzak_morphy
        working-directory: ./zikzak_morphy
        run: |
          dart pub get
          dart analyze

      - name: Run tests zikzak_morphy
        working-directory: ./zikzak_morphy
        run: dart test

      - name: Setup factory_test
        working-directory: ./factory_test
        run: |
          dart pub get
          dart run build_runner build --delete-conflicting-outputs

      - name: Run tests factory_test
        working-directory: ./factory_test
        run: dart test

      - name: Setup example
        working-directory: ./example
        run: |
          dart pub get
          dart run build_runner build --delete-conflicting-outputs

      - name: Run tests example
        working-directory: ./example
        run: dart test
